apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trace-demo-service-a
  name: trace-demo-service-a
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trace-demo-service-a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trace-demo-service-a
    spec:
      containers:
      - image: gcr.io/sej-step05-sandbox/trace-demo-service-a-java:v3
        imagePullPolicy: IfNotPresent
        name: trace-demo-service-a-java
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
