apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-01-26T03:47:01Z"
  generation: 3
  labels:
    app: trace-demo-service-a
  name: trace-demo-service-a
  namespace: default
  resourceVersion: "5834161"
  uid: 111b6522-6ab5-4df4-9356-91e0d07d0ebf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trace-demo-service-a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trace-demo-service-a
    spec:
      containers:
      - image: gcr.io/longz-prem-bd/trace-demo-service-a-java:v3
        imagePullPolicy: IfNotPresent
        name: trace-demo-service-a-java
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-26T03:47:11Z"
    lastUpdateTime: "2023-01-26T03:47:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-26T03:47:02Z"
    lastUpdateTime: "2023-01-27T04:35:48Z"
    message: ReplicaSet "trace-demo-service-a-6994c58585" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
